### ISSUE TITLE
it it still safe to install 12.1 on android 13 ?

### ISSUE THREAD

**Issue by D0nnieD4rk0** [aHVzY2g/android-device-samsung-a22x#8]
Hi, I'm currently on android 13 and would like to know if it is still safe enough to install twrp for android 12.1 since it is still the same SM-A226B. I'm playing on moving to a GSI rom right after I install twrp.

Cheers

**Comment by aHVzY2g** [comment]
According to this post https://forum.xda-developers.com/t/recovery-unofficial-experimental-alpha-twrp-for-galaxy-a22-5g-sm-a226b.4448857/post-88269537 it does work
