### ISSUE TITLE
decrypt and mount userdata

### ISSUE THREAD

**Issue by EmbGangsta** [aHVzY2g/android-device-samsung-a22x#9]
Hi,

I was able to install your fabulous TWRP 2.00.1 version on a Samsung A226B on which I need to decrypt the USERDATA partition that is for now still not readable from TWRP.

I saw on forums that in some other officials TWRP images (example with 2.7.0 for other device) that there was a "adb shell twrp decrypt" command that worked for some people with the pattern unlock password as passcode to decrypt userdata.

I did a full ROM dump of my phone thanks to SP flash tool and MTK WWR tool some week ago. 
I have all partition elements saved to files including userdata.img as a big big ~50Gb file. However I know that this file is most probably encrypted with some keys inside the phone such as screen lock or other thing and I have to use the phone itself to decrypt that. If I factory reset the phone I won't be able to decrypt data anymore because keys will be reset as well ...

So I was interested doing it with TWRP but the userdata for now is not seen and cannot be mounted and need to be decrypted.

But my question is : is this 2.00.1 alpha version nearly ready to handle this ? What would be the effort ?

Best Regards

**Comment by aHVzY2g** [comment]
Hi @EmbGangsta,

this TWRP build does not handle the decryption and I unfortunately can't answer your question. I don't use this phone as a daily driver, and so I am not interested in supporting this feature at the moment. If you want to try it yourself, the folks here https://t.me/build_twrp/1 are great. Good luck, MTK phones are quite an experience :D.

**Comment by EmbGangsta** [comment]
Thanks for your time ! I will try to create build environment and make a contribution for that purpose
